name: Package

on:
  release:
    types: [ created ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package
        id: package
        run: |
            curl -LO https://github.com/telppa/PaddleOCR-AutoHotkey/releases/download/v20220110/PaddleOCR-AutoHotkey_EN.zip -o gehennaspack/PaddleOCR.zip
            ls -al gehennaspack/
            unzip gehennaspack/PaddleOCR -d gehennaspack/PaddleOCR/
            git archive HEAD --format=zip --worktree-attributes --prefix="gehennaspack/" -o "gehennaspack-${{ github.event.release.tag_name }}.zip"

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: gehennaspack/gehennaspack-${{ github.event.release.tag_name }}.zip
          asset_path: ./gehennaspack/gehennaspack-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
