name: Package
on: 
  release:
    types: [published]
  
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: wget
        uses: wei/wget@v1
        with:
          args: -qO- https://github.com/telppa/PaddleOCR-AutoHotkey/releases/download/v20220110/PaddleOCR-AutoHotkey_EN.zip -O gehennaspack/PaddleOCR.zip
      - name: Package
        id: package
        run: |
            ls -al gehennaspack/
            cp gehennaspack/run.ahk gehennaspack-${{ github.event.release.tag_name }}.ahk
            unzip gehennaspack/PaddleOCR.zip -d gehennaspack/
            mv gehennaspack/PaddleOCR-AutoHotkey/PaddleOCR gehennaspack/PaddleOCR
            rm gehennaspack/PaddleOCR.zip
            rm -rf gehennaspack/PaddleOCR-AutoHotkey
            ls -al gehennaspack/
            zip -r gehennaspack-${{ github.event.release.tag_name }}.zip gehennaspack/
            echo ${{ github.event.release.assets }}

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          assets: |
            *.tar.gz
            *.zip
      - name: Upload with deps
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: gehennaspack-${{ github.event.release.tag_name }}.zip
          asset_path: ./gehennaspack-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: Upload without deps
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: gehennaspack-${{ github.event.release.tag_name }}.ahk
          asset_path: ./gehennaspack-${{ github.event.release.tag_name }}.ahk
          asset_content_type: text/plain
